### ISSUE TITLE
Help Wanted Cannot get API from disgenet2r

### ISSUE THREAD

**Issue by WanghcPKU** [jinfar/disgenet2r#1]
Hello! I got a little problem when I was using disgenet2r.

I used this function to get API from R session
disgenet_api_key <- get_disgenet_api_key(
                  email = "myemail", 
                  password = "mypassword" )

But I got an error:

$category
[1] "Client error"

$reason
[1] "Not Found"

$message
[1] "Client error: (404) Not Found"

[1] "<h1>Not Found</h1><p>The requested resource was not found on this server.</p>"
[1] "no results for the query"

I tried to type the DisGeNET API key from website,  and I still got this error

Sys.setenv(DISGENET_API_KEY= "*****************")

$category
[1] "Client error"

$reason
[1] "Not Found"

$message
[1] "Client error: (404) Not Found"

[1] "<h1>Not Found</h1><p>The requested resource was not found on this server.</p>"
[1] "no results for the query"

Could you please help me to solve this problem?

**Comment by Z-Zen** [comment]
seems like they have a problem with the authentification [API](https://www.disgenet.org/api/)

**Comment by Lab-CoMBINE** [comment]
June 9th 2024. They still have problems. Is the project discontinued? 
I also tried to get and use the API directly from the site but it still doesnt work and it returns the same error.

**Comment by zhu197727** [comment]
I also have this problem！！！

**Comment by tfkillian** [comment]
I report the same error.

**Comment by WanghcPKU** [comment]
Hallo ! There is a new R package named disgenetplus. It is just like disgenet2r
